name: Tests-Mac

on:
    - workflow_dispatch

jobs:
    test-mac:
        name: Test on macOS
        runs-on: macOS-latest
        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-python@v5
              with:
                python-version: "3.10"

            - name: Install hatch
              run: python -m pip install hatch

            - name: Run pytest using hatch
              run: hatch run test
