name: Tests

on:
    - push

jobs:
    test:
        name: Test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-python@v5
              with:
                python-version: "3.10"

            - name: Install ffmpeg for playsound tests
              run: sudo apt-get update && sudo apt-get install -y ffmpeg

            - name: Install hatch
              run: python -m pip install hatch

            - name: Run pytest using hatch
              run: hatch run test

            # -- The text matrix worked, but no need to run it on every push.
            # - name: Run test matrix using hatch
            #   run: hatch run test:test
